
database=postgres
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql:///pet-clinic?cloudSqlInstance=fluted-haven-452023-g2:us-central1:digital-mysql03&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=pet-clinic&useSSL=false}
